### ISSUE TITLE
How is deployment order taken care of if not specified explicitly in modules array?

### ISSUE THREAD

**Issue by s1mrankaur** [fourTheorem/slic-starter#129]
I see that the modules are defined in order so that should resolve order of deployment correctly but what's the best way to do it without having to explicitly say order of modules in CI/CD as I would like to keep them dynamically findable by the CI/CD and not hardcode the names and order of modules

**Comment by eoinsha** [comment]
Hi @s1mrankaur. Deployment order is not predictable by design. All modules are deployed in parallel in a fail-fast strategy. As a result, initial deployments will fail due to unfulfilled dependencies. Once the first deployment is working, subsequent changes should maintain backward compatibility or avoid coupling to prevent this. I hope this answers your question.

**Comment by s1mrankaur** [comment]
@eoinsha  Thank you for your response. Where is the code for "fail-fast strategy" exactly? Do you mean that it automatically attempts to re-deploy the modules that failed? Where can I see this happening?
